import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  countLimit: { backgroundColor: '#FF416C' },
  card: { padding: 0, gap: 0, overflow: 'hidden' },
  author: {
    padding: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: '#E9ECEF80',
    flexDirection: 'row',
    gap: 12,
  },
  avatarRing: { width: 44, height: 44, borderRadius: 22, padding: 2 },
  avatarBorder: { borderWidth: 2, borderColor: '#FFF', borderRadius: 20 },
  star: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#FF416C',
    color: '#FFF',
    fontSize: 9,
    lineHeight: 16,
    textAlign: 'center',
    overflow: 'hidden',
  },
  authorCopy: { flex: 1, justifyContent: 'center', gap: 2 },
  authorNameRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  authorName: { flexShrink: 1, fontSize: 14.5, lineHeight: 21.75, color: '#1A1A1A' },
  topic: {
    fontSize: 10,
    lineHeight: 15,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#FF416C33',
    backgroundColor: '#FF416C1A',
    color: '#FF416C',
    overflow: 'hidden',
  },
  metadata: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  rank: { fontSize: 11, lineHeight: 16.5, color: '#FF416C' },
  local: { fontSize: 11, lineHeight: 16.5, color: '#E17100' },
  distance: { fontSize: 11, lineHeight: 16.5, color: '#1A1A1A' },
  dot: { color: '#4A4A4A', fontSize: 11, marginHorizontal: 3 },
  body: { padding: 16, gap: 13 },
  input: {
    height: 87,
    padding: 0,
    borderWidth: 0,
    fontSize: 15,
    lineHeight: 24.375,
    fontFamily: 'BeVietnamPro_500Medium',
    borderRadius: 0,
  },
  photos: { gap: 8 },
  photo: {
    width: 92,
    height: 92,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    borderRadius: 14,
    overflow: 'hidden',
  },
  image: { width: 90, height: 90 },
  photoTag: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    borderRadius: 2.222,
    paddingHorizontal: 4,
    backgroundColor: '#00000099',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  photoTagText: { fontSize: 8, lineHeight: 12, color: '#FFF' },
  remove: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#000000B3',
    justifyContent: 'center',
    alignItems: 'center',
  },
  add: {
    width: 92,
    height: 92,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#FF416C66',
    backgroundColor: '#FF416C0D',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  addText: { fontSize: 10, lineHeight: 15, color: '#FF416C' },
  toolbar: {
    borderTopWidth: 1,
    borderColor: '#E9ECEF',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tools: { flexDirection: 'row', gap: 6 },
  tool: {
    width: 30,
    height: 30,
    borderRadius: 8.333,
    backgroundColor: '#F1F3F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  countRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  count: { fontSize: 11, lineHeight: 16.5, color: '#4A4A4A' },
  countDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#00BC7D' },
});
