import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F8F9FA' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    backgroundColor: '#FFF',
    borderBottomWidth: 1,
    borderColor: '#E9ECEF',
  },
  cancel: { fontSize: 14, lineHeight: 21, color: '#4A4A4A' },
  title: { fontSize: 16, lineHeight: 24, color: '#1A1A1A' },
  content: { flexGrow: 1 },
  author: { padding: 20, flexDirection: 'row', alignItems: 'center', gap: 12 },
  copy: { flex: 1 },
  name: { fontSize: 14, lineHeight: 21, color: '#1A1A1A' },
  meta: { fontSize: 11, lineHeight: 13.75, color: '#4A4A4A' },
  editorSection: { paddingHorizontal: 20, gap: 24, flexGrow: 1 },
  editor: {
    height: 452.5,
    padding: 32,
    backgroundColor: '#FFF',
    borderWidth: 2,
    borderColor: '#E9ECEFB3',
    borderRadius: 30.667,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 1,
    shadowOffset: { width: 0, height: 1 },
  },
  input: {
    height: 200,
    padding: 0,
    borderWidth: 0,
    borderRadius: 0,
    fontFamily: 'BeVietnamPro_900Black',
    fontSize: 24,
    lineHeight: 32,
    textAlign: 'center',
  },
  palette: { flexDirection: 'row', justifyContent: 'center', gap: 12 },
  swatch: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#FFF',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
  },
  selected: { boxShadow: '0 0 0 3px #FF416C33' },
  footer: { padding: 20, paddingBottom: 0, gap: 14 },
});
