import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F8F9FA' },
  content: { paddingHorizontal: 16, paddingBottom: 104, gap: 16 },
  headerOverlay: { position: 'absolute', top: 0, left: 0, right: 0, paddingTop: 48, paddingBottom: 15, paddingHorizontal: 16, backgroundColor: '#F8F9FAF2', borderBottomWidth: 1, borderBottomColor: '#E9ECEFCC', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  backButton: { width: 36, height: 36, borderRadius: 10, borderWidth: 1, borderColor: '#E9ECEF', backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 18, lineHeight: 28, color: '#1A1A1A' },
  headerSubtitle: { fontSize: 11, lineHeight: 16.5, color: '#4A4A4A' },
  prizeButton: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 15, paddingVertical: 7, borderRadius: 999, borderWidth: 1, borderColor: '#FF416C4D', backgroundColor: '#FF416C26', overflow: 'hidden' },
  prizeButtonText: { color: '#FF416C', fontSize: 12, lineHeight: 16 },
  periodPicker: { height: 52, padding: 7, borderRadius: 14, borderWidth: 1, borderColor: '#E9ECEF', backgroundColor: '#FFF', flexDirection: 'row', alignItems: 'center', gap: 4, shadowColor: '#000', shadowOpacity: 0.05, shadowOffset: { width: 0, height: 1 }, shadowRadius: 0 },
  periodButton: { flex: 1, minHeight: 36, borderRadius: 10, paddingHorizontal: 4, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  periodActive: { backgroundColor: 'transparent', overflow: 'hidden' },
  periodText: { fontSize: 12, lineHeight: 16, color: '#FFF' },
  periodInactive: { color: '#4A4A4A' },
  calendarButton: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  heroCard: { minHeight: 240, padding: 21, borderRadius: 31, borderWidth: 1, borderColor: '#FF416C33', overflow: 'hidden', gap: 20, shadowColor: '#000', shadowOpacity: 0.08, shadowOffset: { width: 0, height: 1 }, shadowRadius: 3 },
  heroHeader: { paddingBottom: 13, borderBottomWidth: 1, borderBottomColor: '#E9ECEF99', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  heroHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  medalBadge: { width: 28, height: 28, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  heroLabel: { fontSize: 10, lineHeight: 15, letterSpacing: 0.5, color: '#4A4A4A' },
  heroAmount: { fontSize: 14, lineHeight: 20 },
  daysPill: { paddingHorizontal: 11, paddingVertical: 5, borderRadius: 999, borderWidth: 1, borderColor: '#FE9A0033', backgroundColor: '#FE9A001A', flexDirection: 'row', alignItems: 'center', gap: 6 },
  daysText: { fontSize: 12, lineHeight: 16, color: '#FFB900' },
  podiumRow: { height: 171.5, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  podiumItem: { flex: 1, marginHorizontal: 3.66, height: 159, alignItems: 'center', justifyContent: 'flex-end', position: 'relative' },
  podiumSecond: { height: 168 },
  podiumFirst: { height: 188, marginBottom: -0.5 },
  podiumAvatarRing: { position: 'absolute', top: 0, alignItems: 'center', justifyContent: 'center', borderWidth: 2 },
  silverRing: { borderColor: '#CAD5E2' },
  goldRing: { borderColor: '#FFB900', shadowColor: '#FFB900', shadowOpacity: 0.4, shadowRadius: 14, shadowOffset: { width: 0, height: 0 } },
  bronzeRing: { borderColor: '#D97706' },
  placeBadge: { position: 'absolute', right: -2, bottom: -2, width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  placeFirst: { borderWidth: 2, borderColor: '#1D293D', width: 26, height: 26, borderRadius: 13, right: 2, backgroundColor: '#FE9A00' },
  placeSecond: { backgroundColor: '#314158' },
  placeThird: { width: 20, height: 20, borderRadius: 10, backgroundColor: '#B45309' },
  placeText: { color: '#FFF', fontSize: 11, lineHeight: 16.5 },
  crown: { position: 'absolute', top: -22, alignSelf: 'center' },
  podiumName: { position: 'absolute', top: 72, left: 0, right: 0, alignItems: 'center' },
  podiumNameText: { fontSize: 12, lineHeight: 16, color: '#1A1A1A' },
  podiumScore: { position: 'absolute', top: 90, flexDirection: 'row', alignItems: 'baseline' },
  podiumScoreText: { fontSize: 12, lineHeight: 16, color: '#FF416C' },
  podiumUnit: { fontSize: 9.5, lineHeight: 12, color: '#4A4A4A' },
  podiumReward: { overflow: 'hidden', width: '100%', paddingTop: 9, paddingBottom: 11, borderRadius: 15, alignItems: 'center', gap: 2 },
  silverReward: { backgroundColor: '#F1F3F599', borderWidth: 1, borderColor: '#E9ECEFCC' },
  goldReward: { backgroundColor: '#FF416C26', borderWidth: 1, borderColor: '#FF416C4D' },
  bronzeReward: { backgroundColor: '#A86024', borderWidth: 1, borderColor: '#E5A663' },
  rewardLabel: { fontSize: 9, lineHeight: 13.5, letterSpacing: 0.45, color: '#4A4A4A' },
  rewardAmount: { fontSize: 11, lineHeight: 16.5, color: '#1A1A1A' },
  goldRewardLabel: { color: '#FF416C' },
  goldRewardAmount: { color: '#FF416C', fontSize: 12, lineHeight: 18 },
  bronzeRewardLabel: { color: '#FFE8D1', fontSize: 9.5, lineHeight: 14.25, letterSpacing: 0.475 },
  bronzeRewardAmount: { color: '#FFF', fontSize: 12, lineHeight: 18 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 0 },
  sectionTitle: { fontSize: 12, lineHeight: 16, letterSpacing: 0.6, color: '#4A4A4A' },
  updated: { fontSize: 11, lineHeight: 16.5, color: '#4A4A4A' },
  rows: { gap: 10 },
  communityRow: { minHeight: 60, padding: 13, borderRadius: 19, borderWidth: 1, borderColor: '#E9ECEF', backgroundColor: '#FFF', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', shadowColor: '#000', shadowOpacity: 0.05, shadowOffset: { width: 0, height: 1 }, shadowRadius: 0 },
  currentRow: { backgroundColor: '#FF416C0D', borderColor: '#FF416C4D' },
  communityLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  communityRank: { width: 24, textAlign: 'center', fontSize: 14, lineHeight: 20, color: '#4A4A4A' },
  currentText: { color: '#FF416C' },
  communityCopy: { flex: 1 },
  communityNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  communityName: { flexShrink: 1, fontSize: 14, lineHeight: 20, color: '#1A1A1A' },
  communityMeta: { fontSize: 11, lineHeight: 16.5, color: '#4A4A4A' },
  youPill: { paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3, backgroundColor: '#FF416C', color: '#FFF', fontSize: 9, lineHeight: 13.5 },
  communityScore: { width: 72, alignItems: 'flex-end' },
  pointsRow: { flexDirection: 'row', alignItems: 'baseline' },
  points: { fontSize: 14, lineHeight: 20, color: '#1A1A1A' },
  pointsUnit: { fontSize: 10, lineHeight: 14, color: '#4A4A4A' },
  communityReward: { marginTop: 8, paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3, backgroundColor: '#00BC7D1A', color: '#00D492', fontSize: 10, lineHeight: 15 },
  stickyRank: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 14, paddingTop: 15, paddingBottom: 14, borderTopWidth: 1, borderTopColor: '#FF416C4D', backgroundColor: '#FFFFFFF2', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', shadowColor: '#000', shadowOpacity: 0.1, shadowOffset: { width: 0, height: -4 }, shadowRadius: 8 },
  stickyLeft: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 12 },
  rankBadge: { width: 32, height: 32, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  rankBadgeText: { color: '#FFF', fontSize: 12, lineHeight: 16 },
  stickyAvatar: { width: 36, height: 36, borderRadius: 18, borderWidth: 2, borderColor: '#FF416C' },
  stickyCopy: { flex: 1 },
  stickyNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  stickyName: { fontSize: 12, lineHeight: 16, color: '#1A1A1A' },
  topPill: { paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3, backgroundColor: '#FF416C26', color: '#FF416C', fontSize: 9.5, lineHeight: 14.25 },
  stickyHint: { fontSize: 10.5, lineHeight: 15.75, color: '#4A4A4A' },
  stickyScore: { width: 75, alignItems: 'flex-end' },
  scoreText: { fontSize: 14, lineHeight: 20 },
  scoreUnit: { fontSize: 10, lineHeight: 14 },
  rewardPill: { marginTop: 5, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, backgroundColor: '#00BC7D1A', color: '#00D492', fontSize: 10, lineHeight: 15 },
});
